WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
*** SIGABRT received at time=1652928720 on cpu 3 ***
PC: @     0x7f5647336428  (unknown)  raise
    @     0x7f56476dc390       3904  (unknown)
    @     0x7f55e92a6cb1         48  llvm::report_fatal_error()
    @     0x7f55e9238100         96  ReportErrnumFatal()
    @     0x7f55e92382f8        128  llvm::llvm_execute_on_thread_impl()
    @     0x7f55e923879d         48  llvm::thread::thread<>()
    @     0x7f55e923a871        144  llvm::ThreadPool::ThreadPool()
    @     0x7f55e915074f        496  mlir::MLIRContext::MLIRContext()
    @     0x7f55e9150a19        160  mlir::MLIRContext::MLIRContext()
    @     0x7f55e6e260cc       2528  xla::cpu::CpuCompiler::RunBackend()
    @     0x7f55e6e1257a       4432  xla::TfrtCpuClient::Compile()
    @     0x7f55e6d512b5        976  xla::PyClient::Compile()
    @     0x7f55e6abbb5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
    @     0x7f55e6abc434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7f55e6a9d821        544  pybind11::cpp_function::dispatcher()
    @     0x55c731bfe562  274511544  _PyCFunction_FastCallDict
    @     0x55c731d6e660  (unknown)  (unknown)
[2022-05-19 08:22:00,603 E 72029 84767] logging.cc:325: *** SIGABRT received at time=1652928720 on cpu 3 ***
[2022-05-19 08:22:00,603 E 72029 84767] logging.cc:325: PC: @     0x7f5647336428  (unknown)  raise
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f56476dc390       3904  (unknown)
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e92a6cb1         48  llvm::report_fatal_error()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e9238100         96  ReportErrnumFatal()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e92382f8        128  llvm::llvm_execute_on_thread_impl()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e923879d         48  llvm::thread::thread<>()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e923a871        144  llvm::ThreadPool::ThreadPool()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e915074f        496  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e9150a19        160  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e6e260cc       2528  xla::cpu::CpuCompiler::RunBackend()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e6e1257a       4432  xla::TfrtCpuClient::Compile()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e6d512b5        976  xla::PyClient::Compile()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e6abbb5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e6abc434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x7f55e6a9d821        544  pybind11::cpp_function::dispatcher()
[2022-05-19 08:22:00,608 E 72029 84767] logging.cc:325:     @     0x55c731bfe562  274511544  _PyCFunction_FastCallDict
[2022-05-19 08:22:00,612 E 72029 84767] logging.cc:325:     @     0x55c731d6e660  (unknown)  (unknown)
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 360 in backend_compile
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 297 in xla_primitive_callable
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 179 in cached
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 186 in wrapper
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 248 in apply_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 603 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 348 in mul
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 1522 in isclose
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 233 in mismatch_function
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/linear_util.py", line 166 in call_wrapped
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 505 in trace_to_jaxpr
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 102 in linearize
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 115 in vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 1997 in _vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 901 in value_and_grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 829 in grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 123 in backward
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/torch/autograd/function.py", line 77 in apply
Command terminated by signal 6
6.69user 4.02system 0:27.35elapsed 39%CPU (0avgtext+0avgdata 1980440maxresident)k
1888inputs+48outputs (0major+320169minor)pagefaults 0swaps
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
*** SIGABRT received at time=1652929023 on cpu 29 ***
PC: @     0x7f202118c428  (unknown)  raise
    @     0x7f2021532390       3872  (unknown)
    @     0x7f1fc30fccb1         48  llvm::report_fatal_error()
    @     0x7f1fc308e100         96  ReportErrnumFatal()
    @     0x7f1fc308e2f8        128  llvm::llvm_execute_on_thread_impl()
    @     0x7f1fc308e79d         48  llvm::thread::thread<>()
    @     0x7f1fc3090871        144  llvm::ThreadPool::ThreadPool()
    @     0x7f1fc2fa674f        496  mlir::MLIRContext::MLIRContext()
    @     0x7f1fc2fa6a19        160  mlir::MLIRContext::MLIRContext()
    @     0x7f1fc0c7c0cc       2528  xla::cpu::CpuCompiler::RunBackend()
    @     0x7f1fc0c6857a       4432  xla::TfrtCpuClient::Compile()
    @     0x7f1fc0ba72b5        976  xla::PyClient::Compile()
    @     0x7f1fc0911b5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
    @     0x7f1fc0912434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7f1fc08f3821        544  pybind11::cpp_function::dispatcher()
    @     0x5596da2af562  (unknown)  _PyCFunction_FastCallDict
    @     0x5596da41f660  (unknown)  (unknown)
[2022-05-19 08:27:03,845 E 100470 103175] logging.cc:325: *** SIGABRT received at time=1652929023 on cpu 29 ***
[2022-05-19 08:27:03,845 E 100470 103175] logging.cc:325: PC: @     0x7f202118c428  (unknown)  raise
[2022-05-19 08:27:03,849 E 100470 103175] logging.cc:325:     @     0x7f2021532390       3872  (unknown)
[2022-05-19 08:27:03,849 E 100470 103175] logging.cc:325:     @     0x7f1fc30fccb1         48  llvm::report_fatal_error()
[2022-05-19 08:27:03,849 E 100470 103175] logging.cc:325:     @     0x7f1fc308e100         96  ReportErrnumFatal()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x7f1fc308e2f8        128  llvm::llvm_execute_on_thread_impl()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x7f1fc308e79d         48  llvm::thread::thread<>()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x7f1fc3090871        144  llvm::ThreadPool::ThreadPool()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x7f1fc2fa674f        496  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x7f1fc2fa6a19        160  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x7f1fc0c7c0cc       2528  xla::cpu::CpuCompiler::RunBackend()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x7f1fc0c6857a       4432  xla::TfrtCpuClient::Compile()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x7f1fc0ba72b5        976  xla::PyClient::Compile()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x7f1fc0911b5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x7f1fc0912434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x7f1fc08f3821        544  pybind11::cpp_function::dispatcher()
[2022-05-19 08:27:03,850 E 100470 103175] logging.cc:325:     @     0x5596da2af562  (unknown)  _PyCFunction_FastCallDict
[2022-05-19 08:27:03,855 E 100470 103175] logging.cc:325:     @     0x5596da41f660  (unknown)  (unknown)
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 360 in backend_compile
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 297 in xla_primitive_callable
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 179 in cached
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 186 in wrapper
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 248 in apply_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 603 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 735 in broadcast_in_dim
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 720 in broadcast
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 1589 in full
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 3135 in zeros
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/utils/comboptnet_utils.py", line 62 in compute_delta_y
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 222 in mismatch_function
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/linear_util.py", line 166 in call_wrapped
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 505 in trace_to_jaxpr
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 102 in linearize
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 115 in vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 1997 in _vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 901 in value_and_grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 829 in grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 123 in backward
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/torch/autograd/function.py", line 77 in apply
Command terminated by signal 6
5.67user 1.74system 0:23.01elapsed 32%CPU (0avgtext+0avgdata 1979148maxresident)k
0inputs+48outputs (0major+308985minor)pagefaults 0swaps
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
